# Generated by Django 3.2.5 on 2021-07-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('passport', models.IntegerField()),
                ('tel', models.IntegerField()),
                ('comeform', models.TextField()),
                ('terminus', models.TextField()),
            ],
        ),
    ]
