# Generated by Django 3.2.5 on 2021-07-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('passport', models.CharField(max_length=18)),
                ('tel', models.CharField(max_length=18)),
                ('country', models.CharField(default='-', max_length=255)),
                ('comeform', models.TextField()),
                ('district', models.CharField(default='-', max_length=255)),
                ('canton', models.CharField(default='-', max_length=255)),
                ('terminus', models.TextField()),
                ('ldistrict', models.CharField(default='-', max_length=255)),
                ('lcanton', models.CharField(default='-', max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='pageimage')),
            ],
            options={
                'db_table': 'page_post',
            },
        ),
    ]
