# Generated by Django 3.2.5 on 2021-07-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20210703_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='canton',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='country',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='district',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='lcanton',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='ldistrict',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.TimeField(default='0'),
        ),
        migrations.AlterField(
            model_name='post',
            name='passport',
            field=models.CharField(max_length=18),
        ),
    ]
